# cf http://qiita.com/pine613/items/3fdc4e1bd06065cc056d
build: off
shallow_clone: true
init:
  - git config --global core.autocrlf input
install:
  - choco install strawberryperl --version 5.24.1.1
  - SET "PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%"
  - cpanm -nq --installdeps --with-develop .
test_script:
  - prove -l t xt
